language: rust
rust: nightly
cache: cargo

jobs:
  include:
    - stage: test
      script: cargo test --verbose
    - stage: deploy-resin
      install: skip
      script:
        - eval "$(ssh-agent -s)" #start the ssh agent
        - echo -e $RESIN_DEPLOY_KEY > id_rsa
        - chmod 0600 id_rsa
        - ssh-add ./id_rsa
        - cat resinkey >> ~/.ssh/known_hosts
        - git remote add resin $RESIN_REMOTE
        - git push resin master

stages:
  - test
  - name: deploy-resin
    if: branch = master
