[package]
name = "hello-resin"
version = "0.1.0"
authors = ["Callum Dunster <calonthexbox@hotmail.com>"]

[dependencies]
rocket = "0.3.17"
rocket_codegen = "0.3.17"
rocket_contrib = "0.3.17"
serde = "1.0.79"
serde_json = "*"
