[package]
name = "smart-home"
version = "0.1.0"

[dependencies]
rocket = "0.4.*"
rocket_contrib = {version = "0.4.*", default-features = false, features = ["uuid", "json"]}
serde = "1.0.*"
serde_json = "1.0.*"
serde_derive = "1.0.*"
uuid = { version = "0.7.*", features = ["serde", "v4"] }
