[package]
name = "hello-resin"
version = "0.1.0"
authors = ["Callum Dunster <calonthexbox@hotmail.com>"]

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket" }
