openapi: "3.0.0"
info:
  title: Home Automation in Rust
  version: "1.0.0"
  description: This is the public API that can be used to control the system.

paths:
  /zones:
    get:
      tags:
        - Zones
      summary: List all the zones in the system.
      responses:
        "200":
          description: OK - Body contains object with list of zones.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Zones"

  /zones/{zoneUuid}:
    get:
      tags:
        - Zones
      summary: Get the details of the specified zone.
      parameters:
        - name: zoneUuid
          in: path
          description: The unique identifier of the desired zone.
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK - Body contains Zone object.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Zone"

components:
  schemas:
    Zone:
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
          uniqueItems: true
          description: Unique identifier for a Zone.
          example: 7bd897d5-195c-4fc3-8d34-59d960d94a33
        name:
          type: string
          description: User-friendly name for the Zone.
          uniqueItems: true
          maxLength: 24
          example: Living Room

    Zones:
      type: object
      properties:
        zones:
          type: array
          items:
            $ref: "#components/schemas/Zone"
