openapi: "3.0.0"
info:
  title: Home Automation in Rust
  version: "1.0.0"
  description: This is the public API that can be used to control the system.

paths:
  /zones:
    get:
      tags:
        - Zones
      summary: List all the zones in the system.
      responses:
        200:
          description: OK - Body contains object with list of zones.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Zones"
    put:
      tags:
        - Zones
      summary: Add a new zone to the list of zones.
      requestBody:
        description: The new zone to be added.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Zone"
      responses:
        201:
          description: CREATED - Empty response body.

  /zones/{zoneUuid}:
    get:
      tags:
        - Zones
      summary: Get the details of the specified zone.
      parameters:
        - name: zoneUuid
          in: path
          description: The unique identifier of the desired zone.
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK - Body contains Zone object.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Zone"

components:
  schemas:
    Zone:
      type: object
      properties:
        name:
          type: string
          description: User-friendly name for the Zone.
          uniqueItems: true
          maxLength: 24
          example: Living Room

    Zones:
      type: object
      properties:
        zones:
          type: object
          additionalProperties:
            $ref: "#components/schemas/Zone"
          example:
            "8a70d6f5-a877-4331-8f15-0f20e4d34c0f": { "name": Living Room }
            "a805847b-0df2-44b8-9a49-b3aebd8eecb2": { "name": Bedroom }
